// Builds a fully static copy of the prototype into dist/, for free static hosting
// (GitHub Pages, Netlify, Cloudflare Pages). Zero dependencies, like the rest of the repo.
//
//   node scripts/build-static.js
//
// Nothing in server/ or public/ is changed. The real server modules (engine, store,
// API routes) are bundled as-is into dist/js/engine.bundle.js, and a small shim answers
// the page's fetch('/api/...') calls in the browser by running them through the same
// handleApi(). The per-browser sandbox the server keeps in memory is persisted to
// localStorage instead, so Driver, Customer and Hub tabs stay in sync across reloads.
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const PUBLIC = path.join(ROOT, 'public');
const DIST = path.join(ROOT, 'dist');

const MODULES = [
  'server/config.js',
  'server/lib/errors.js',
  'server/lib/format.js',
  'server/lib/geo.js',
  'server/engine/telemetry.js',
  'server/engine/verification.js',
  'server/engine/router.js',
  'server/engine/eligibility.js',
  'server/engine/offer.js',
  'server/engine/recovery.js',
  'server/engine/customers.js',
  'server/data/seed.js',
  'server/store.js',
  'server/api.js',
];

function copyDir(src, dst) {
  fs.mkdirSync(dst, { recursive: true });
  for (const e of fs.readdirSync(src, { withFileTypes: true })) {
    const s = path.join(src, e.name);
    const d = path.join(dst, e.name);
    if (e.isDirectory()) copyDir(s, d);
    else fs.copyFileSync(s, d);
  }
}

function bundle() {
  const seed = fs.readFileSync(path.join(ROOT, 'server/data/seed.json'), 'utf8');
  const defs = MODULES.map((id) => {
    let src = fs.readFileSync(path.join(ROOT, id), 'utf8');
    // Let the shim read and restore the sandbox map (it is module-private on the server).
    if (id === 'server/store.js') src += '\nmodule.exports.__sessions = sessions;\n';
    return `${JSON.stringify(id)}: function (require, module, exports, __dirname) {\n${src}\n}`;
  });

  return `// Generated by scripts/build-static.js — do not edit. Source: server/
(function () {
  'use strict';
  var process = { env: {} };
  var SEED_JSON = ${JSON.stringify(seed)};
  var builtins = {
    fs: { readFileSync: function () { return SEED_JSON; } },
    path: { join: function () { return Array.prototype.join.call(arguments, '/'); } },
  };
  var defs = {
${defs.join(',\n')}
  };
  var cache = {};
  function resolve(from, req) {
    if (req[0] !== '.') return req;
    var parts = from.split('/'); parts.pop();
    req.split('/').forEach(function (seg) {
      if (seg === '..') parts.pop(); else if (seg !== '.') parts.push(seg);
    });
    var id = parts.join('/');
    return /\\.js$/.test(id) ? id : id + '.js';
  }
  function load(id) {
    if (builtins[id]) return builtins[id];
    if (cache[id]) return cache[id].exports;
    if (!defs[id]) throw new Error('Module not bundled: ' + id);
    var module = (cache[id] = { exports: {} });
    defs[id](function (req) { return load(resolve(id, req)); }, module, module.exports, id.replace(/\\/[^/]*$/, ''));
    return module.exports;
  }

  var api = load('server/api.js');
  var sessions = load('server/store.js').__sessions;
  var KEY = 'rto-static-sandbox';

  function restore() {
    try {
      var raw = localStorage.getItem(KEY);
      if (!raw) return;
      sessions.clear();
      JSON.parse(raw).forEach(function (kv) { sessions.set(kv[0], kv[1]); });
    } catch (e) { /* private mode: fall back to in-memory only */ }
  }
  function persist() {
    try { localStorage.setItem(KEY, JSON.stringify(Array.from(sessions.entries()))); } catch (e) {}
  }

  var realFetch = window.fetch.bind(window);
  window.fetch = function (input, init) {
    init = init || {};
    var url = new URL(typeof input === 'string' ? input : input.url, location.href);
    if (url.pathname.indexOf('/api/') !== 0) return realFetch(input, init);

    var headers = {};
    Object.keys(init.headers || {}).forEach(function (k) { headers[k.toLowerCase()] = init.headers[k]; });
    var body = init.body || '';
    var req = {
      method: (init.method || 'GET').toUpperCase(),
      headers: headers,
      on: function (ev, cb) {
        if (ev === 'data' && body) queueMicrotask(function () { cb(body); });
        if (ev === 'end') queueMicrotask(function () { cb(); });
      },
    };
    return new Promise(function (resolveRes) {
      var status = 200, resHeaders = {};
      var res = {
        writeHead: function (s, h) { status = s; resHeaders = h || {}; },
        end: function (data) {
          persist();
          resolveRes(new Response(data, { status: status, headers: resHeaders }));
        },
      };
      restore();
      api.handleApi(req, res, url);
    });
  };
})();
`;
}

fs.rmSync(DIST, { recursive: true, force: true });
copyDir(PUBLIC, DIST);
fs.writeFileSync(path.join(DIST, 'js', 'engine.bundle.js'), bundle());

// Relative asset paths so the site also works under a sub-path (e.g. user.github.io/repo/),
// and load the engine before the app module.
const indexPath = path.join(DIST, 'index.html');
let html = fs.readFileSync(indexPath, 'utf8')
  .replace('href="/css/style.css"', 'href="css/style.css"')
  .replace('<script type="module" src="/js/app.js"></script>',
    '<script src="js/engine.bundle.js"></script>\n  <script type="module" src="js/app.js"></script>');
fs.writeFileSync(indexPath, html);
fs.writeFileSync(path.join(DIST, '.nojekyll'), '');

console.log('Static build written to', path.relative(process.cwd(), DIST) || DIST);
